"""Generate navigation and dependency notes from a pinned public ASPECT tree."""
from pathlib import Path
import argparse,hashlib,json,re,shutil

def generate(source,destination,wb_export):
    catalog=destination/'model-catalog';catalog.mkdir(parents=True,exist_ok=True)
    prm_files=sorted(source.rglob('*.prm'))
    inventory=[]
    for p in prm_files:
        relative=p.relative_to(source).as_posix()
        kind='fragment' if 'doc' in p.relative_to(source).parts or '.part.' in p.name else 'test' if relative.startswith('tests/') else 'benchmark' if relative.startswith('benchmarks/') else 'model'
        text=p.read_text(errors='replace')
        includes=re.findall(r'^\s*include\s+(.+)$',text,re.M)
        inputs=[]
        for line in text.splitlines():
            match=re.match(r'\s*set\s+(.+?)\s*=\s*(.*?)\s*(?:#.*)?$',line)
            if match and match[2] and re.search(r'file|directory|shared librar',match[1],re.I) and not re.search(r'output|checkpoint|statistics',match[1],re.I):
                inputs.append(match[1]+' = '+match[2])
        assets=[x.name for x in sorted(p.parent.iterdir()) if x.is_file() and x.suffix.lower() in {'.wb','.dat','.txt','.grid','.csv','.json','.gz','.nc','.py','.cc','.h'}]
        body=f'# ASPECT 3.1.0 example: {relative}\n\nSource: https://github.com/geodynamics/aspect/blob/v3.1.0/{relative}\n\n'
        body+=f'Knowledge source: official-3.1.0\nOriginal document kind: {kind}\n\n'
        body+='This is a navigation record. Read the original PRM and its documentation before importing; test files and manual fragments are not standalone production models. Successful indexing does not certify runtime compatibility.\n\n'
        if includes:body+='## Included parameter files\n'+'\n'.join(includes)+'\n\n'
        if inputs:body+='## Input and library settings declared by the example\n'+'\n'.join(inputs)+'\n\n'
        if assets:body+='## Neighboring bundled input files and tools\n'+'\n'.join(assets)+'\n\n'
        if re.search(r'fastscape',text,re.I):body+='FastScape is disabled in this distribution; this example may require a custom solver build.\n'
        if re.search(r'Additional shared libraries',text,re.I):body+='Custom shared libraries must be compiled for this Linux ASPECT/deal.II environment.\n'
        body+='## Description excerpt\n'+ '\n'.join(line.lstrip('# ').strip() for line in text.splitlines()[:30] if line.strip().startswith('#'))+'\n'
        name=hashlib.sha256(relative.encode()).hexdigest()[:20]+'.md'
        (catalog/name).write_text(body)
        inventory.append({'path':relative,'kind':kind,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'catalog':name})
    (catalog/'inventory.json').write_text(json.dumps({'version':'3.1.0','prm_files':inventory},indent=2))
    (catalog/'input-assets.md').write_text('# Using official input assets\n\nASPECT 3.1.0 source files are bundled in /opt/aspect-chat/knowledge/sources/aspect-3.1.0. Input data files above the search size limit are retained there. Numeric table excerpts in search results are not complete datasets. Use the full bundled file, not numbers copied from an excerpt.\n\nASPECT_SOURCE_DIR substitutions point to this stable source tree. Relative paths refer to a case assets directory. Includes are expanded on model import. File existence, coordinate conventions, units, dimensionality and plugin availability must be checked before --validate and runtime. Online OPeNDAP inputs can require internet access. Perple_X and external table-generation programs are not included.\n')
    wb=destination/'world-builder-runtime';wb.mkdir(parents=True,exist_ok=True)
    schema=wb_export/'world_builder_declarations.schema.json'
    shutil.copy2(schema,wb/schema.name)
    shutil.copy2(wb_export/'world_builder_declarations_open.md',wb/'parameters.md')
    payload=json.loads(schema.read_text())
    for name,value in payload.get('properties',{}).items():
        filename=hashlib.sha256(name.encode()).hexdigest()[:20]+'.md'
        (wb/filename).write_text('# World Builder 1.1.1 field: '+name+'\n\nSource: library bundled with the pinned ASPECT image; generated with WorldBuilder::World(..., true, output_dir).\nJSON input format version uses major.minor, e.g. "1.1".\n\n```json\n'+json.dumps(value,indent=2)+'\n```\n')
    (wb/'provenance.md').write_text('# World Builder runtime definitions\n\nLibrary version: 1.1.1. Extracted from the World Builder release library shipped in the pinned upstream ASPECT image, which matches the World Builder version used by the rebuilt ASPECT 3.1.0 executable. The original source and license are bundled under sources/aspect-3.1.0/contrib/world_builder. Official project: https://github.com/GeodynamicWorldBuilder/WorldBuilder\n\nThe JSON schema and documentation were generated by constructing a WorldBuilder::World with has_output_dir=true and an empty cartesian world. The library declares all registered feature models, including unused models; generated definitions are not limited to the empty-world input. Defaults, required fields and units must be checked before creating a .wb file.\n')
    return {'prm_files':len(inventory),'world_builder':'1.1.1'}

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('source',type=Path);p.add_argument('destination',type=Path);p.add_argument('wb_export',type=Path);a=p.parse_args()
    print(json.dumps(generate(a.source,a.destination,a.wb_export)))
