'use strict';
const $=id=>document.getElementById(id);
const icons={
  aspect:'<path d="M3 19 12 4l9 15M7 13h10M5 19h14"/>',edit:'<path d="m15 4 5 5M4 20l4-1 12-12a2 2 0 0 0-4-4L4 15v5Z"/>',upload:'<path d="M12 16V3m-4 4 4-4 4 4M4 15v5h16v-5"/>',file:'<path d="M14 3H5v18h14V8l-5-5Zm0 0v5h5M8 12h8m-8 4h6"/>',settings:'<path d="m9 3-.5 3-2 1.2L4 6.5 2 10l2.5 2L4 15l2 3.5 2.5-.7 2 1.2.5 3h4l.5-3 2-1.2 2.5.7 2-3.5-2.5-2 .5-3-2-3.5-2.5.7-2-1.2-.5-3Z" transform="translate(0 -1) scale(.95)"/><circle cx="12" cy="11" r="3"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',chevron:'<path d="m7 10 5 5 5-5"/>',arrow:'<path d="M12 19V5m-6 6 6-6 6 6"/>',plus:'<path d="M12 4v16M4 12h16"/>',paperclip:'<path d="m8 13 6-6a3 3 0 0 1 4 4l-8 8a5 5 0 0 1-7-7l9-9a2 2 0 0 1 3 3l-8 8"/>',layers:'<path d="m3 8 9-5 9 5-9 5-9-5Zm0 5 9 5 9-5M3 18l9 5 9-5"/>',book:'<path d="M12 5c-3-2-6-2-10-1v15c4-1 7-1 10 1 3-2 6-2 10-1V4c-4-1-7-1-10 1Zm0 0v15"/>',sliders:'<path d="M4 7h16M4 17h16"/><circle cx="8" cy="7" r="2" fill="white"/><circle cx="16" cy="17" r="2" fill="white"/>',folder:'<path d="M3 7V4h6l3 3h9v13H3V7Z"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',terminal:'<path d="m5 6 5 6-5 6m8 0h6"/>',back:'<path d="m10 6-6 6 6 6M4 12h16"/>'
};
function icon(name){return `<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.file}</svg>`;}
function hydrate(root=document){root.querySelectorAll('[data-icon]').forEach(el=>{if(!el.querySelector('svg'))el.insertAdjacentHTML('afterbegin',icon(el.dataset.icon));});}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
let data,lang='en',sessionId,conversation,drawerMode=null,jobId=null,modelData=null,field='density',dirty=false,polling=false,lastMessages='',lastJobs='',lastRequest='',toastTimer;
let selectedAttachments=[];
let engine='aspect',modelFilename=null;
const openLogs=new Set();
const editorDrafts=new Map();
function storePrompt(){if(sessionId)localStorage.setItem('aspect-prompt-'+sessionId,$('prompt').value);}
const token=document.querySelector('meta[name="aspect-token"]').content;
const t=(key,values={})=>{let text=data?.text[key]||key;for(const [k,v] of Object.entries(values))text=text.replaceAll(`{${k}}`,v);return text;};
async function api(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-ASPECT-Token':token},body:JSON.stringify(body)});let result=await response.json();if(!response.ok)throw Error(result.error||response.statusText);return result;}
function toast(text,error=false,duration){$('toast').textContent=text;$('toast').classList.remove('hidden');$('toast').classList.toggle('error',error);clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),duration||(error?6500:3200));}
async function safe(fn){try{return await fn();}catch(error){toast(error.message,true);return null;}}
function translate(){$('runtime-version').textContent='2.0.3';document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.querySelectorAll('[data-t]').forEach(el=>el.textContent=t(el.dataset.t));document.querySelectorAll('[data-placeholder]').forEach(el=>el.placeholder=t(el.dataset.placeholder));document.querySelectorAll('[data-label]').forEach(el=>{el.title=t(el.dataset.label);el.setAttribute('aria-label',t(el.dataset.label));});$('lang-zh').classList.toggle('active',lang==='zh');$('lang-en').classList.toggle('active',lang==='en');hydrate();}
function updateConnection(){const info=data.connection;$('model-name').textContent=info.model||info.name;$('provider-select').innerHTML=data.providers.map(p=>`<option value="${p.id}">${esc(p.id==='custom'?t('custom'):p.name)}</option>`).join('');$('provider-select').value=info.id;$('settings-provider').innerHTML=$('provider-select').innerHTML;$('settings-provider').value=info.id;$('api-url').value=info.url;$('key-state').textContent=t(info.ready?'key_ready':'key_missing');$('vision-hint').textContent=t(info.vision?'vision_yes':'vision_no');$('model-search').value=info.model;$('model-options').innerHTML=info.models.map(m=>`<option value="${esc(m)}">`).join('');renderModelOptions();$('connection-hint').classList.toggle('hidden',info.ready);updateSend();}
function renderModelOptions(){const q=$('model-search').value===data.connection.model?'':$('model-search').value.toLowerCase();const list=data.connection.models.filter(m=>!q||m.toLowerCase().includes(q));$('model-options-list').innerHTML=(list.length?list:data.connection.models).map(m=>`<button class="model-option ${m===data.connection.model?'active':''}" data-model="${esc(m)}">${esc(m)}</button>`).join('');}
function renderHistory(){const items=data.sessions;$('history').innerHTML=items.length?items.map(s=>`<button class="history-item ${s.id===sessionId?'active':''}" data-session="${s.id}" title="${esc(s.title||t('untitled_chat'))}"><span>${esc(s.title||t('untitled_chat'))}</span></button>`).join(''):`<p class="empty-hint">${t('no_history')}</p>`;}
function updateCase(){const id=conversation?.session?.case_id;const name=data.cases.find(c=>c.id===id)?.name;$('context-name').textContent=name||t('model_short');$('context-button').title=name||t('model_unbound');$('case-select').innerHTML=`<option value="">${t('select_case')}</option>`+data.cases.filter(c=>c.engine===engine).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('case-select').value=id||'';}
function storeAttachments(){localStorage.setItem('aspect-attachments-'+sessionId,JSON.stringify(selectedAttachments));renderChips();}
function renderChips(){selectedAttachments=selectedAttachments.filter(id=>data.attachments.some(a=>a.id===id));$('attachment-chips').innerHTML=selectedAttachments.map(id=>{const a=data.attachments.find(a=>a.id===id);return `<div class="file-chip">${icon(a.kind==='pdf'?'book':'file')}<span>${esc(a.name)}</span><button data-remove="${id}" title="${t('close')}">${icon('close')}</button></div>`;}).join('');}
function renderSavedFiles(){$('saved-files').innerHTML=data.attachments.length?data.attachments.map(a=>`<label class="saved-file"><input type="checkbox" value="${a.id}" ${selectedAttachments.includes(a.id)?'checked':''}><span>${esc(a.name)}</span></label>`).join(''):`<p>${t('attachment_empty')}</p>`;}
// Escape source text first; support scientific replies without accepting raw HTML.
function inline(text){let codes=[];text=esc(text).replace(/`([^`]+)`/g,(_,c)=>`\u0000${codes.push(`<code>${c}</code>`)-1}\u0000`);text=text.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>');return text.replace(/\u0000(\d+)\u0000/g,(_,n)=>codes[n]);}
function markdown(source){const lines=source.replace(/\r/g,'').split('\n');let out='',i=0;while(i<lines.length){let line=lines[i];if(/^```/.test(line)){const code=[];i++;while(i<lines.length&&!/^```/.test(lines[i]))code.push(lines[i++]);i++;out+=`<pre><code>${esc(code.join('\n'))}</code></pre>`;continue;}if(!line.trim()){i++;continue;}if(/^#{1,6} /.test(line)){let level=Math.min(3,line.match(/^#+/)[0].length);out+=`<h${level}>${inline(line.replace(/^#+ /,''))}</h${level}>`;i++;continue;}if(line.includes('|')&&i+1<lines.length&&/^\s*\|?\s*:?-+/.test(lines[i+1])){const cells=s=>s.trim().replace(/^\||\|$/g,'').split('|').map(c=>c.trim());const heads=cells(line);i+=2;let rows='';while(i<lines.length&&lines[i].includes('|')&&lines[i].trim()){rows+='<tr>'+cells(lines[i++]).map(c=>`<td>${inline(c)}</td>`).join('')+'</tr>';}out+=`<div class="table-scroll"><table><thead><tr>${heads.map(c=>`<th>${inline(c)}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`;continue;}if(/^\s*([-*+] |\d+\. )/.test(line)){const ordered=/^\s*\d+\./.test(line);let items='';while(i<lines.length&&/^\s*([-*+] |\d+\. )/.test(lines[i]))items+=`<li>${inline(lines[i++].replace(/^\s*([-*+] |\d+\. )/,''))}</li>`;out+=`<${ordered?'ol':'ul'}>${items}</${ordered?'ol':'ul'}>`;continue;}if(/^> /.test(line)){out+=`<blockquote>${inline(line.slice(2))}</blockquote>`;i++;continue;}let para=[line];i++;while(i<lines.length&&lines[i].trim()&&!/^(#{1,6} |```|\s*[-*+] |\s*\d+\. |> )/.test(lines[i])&&!(lines[i].includes('|')&&i+1<lines.length&&/^\s*\|?\s*:?-+/.test(lines[i+1])))para.push(lines[i++]);out+=`<p>${para.map(inline).join('<br>')}</p>`;}return out;}
function renderConversation(force=false){const request=conversation?.request,working=request?.state==='working';renderChatStatus();const signature=JSON.stringify([conversation?.messages,working,request?.event,request?.error]);if(!force&&signature===lastMessages)return;lastMessages=signature;const viewport=$('chat-viewport'),nearBottom=viewport.scrollHeight-viewport.clientHeight-viewport.scrollTop<150;const empty=!conversation?.messages?.length&&!conversation?.session?.case_id;$('app').classList.toggle('empty',empty);$('welcome').classList.toggle('hidden',!empty);$('starters').classList.toggle('hidden',!empty);$('classic-examples').classList.toggle('hidden',!empty);$('messages').innerHTML=(conversation?.messages||[]).map(m=>m.role==='user'?`<article class="message user"><div class="user-bubble">${(m.attachments||[]).map(a=>`<a class="sent-attachment" href="/api/attachment?id=${esc(a.id)}" target="_blank" rel="noopener">${a.kind==='image'?`<img src="/api/attachment?id=${esc(a.id)}" alt="">`:icon(a.kind==='pdf'?'book':'file')}<span>${esc(a.name)}</span></a>`).join('')}${esc(m.content)}</div></article>`:`<article class="message assistant"><div class="assistant-body">${markdown(m.content)}</div></article>`).join('');if(working){const name=request.event?.tool;const label=name?toolLabel(name):t('thinking');$('messages').insertAdjacentHTML('beforeend',`<div class="thinking"><i class="thinking-dot"></i><span>${esc(label)}</span></div>`);}if(request?.state==='error')$('messages').insertAdjacentHTML('beforeend',`<div class="request-error">${esc(request.error)}</div>`);updateSend();if(force||nearBottom)requestAnimationFrame(()=>{viewport.scrollTop=viewport.scrollHeight;});}
function toolLabel(name){const key=name==='search_knowledge'?'retrieving':['modify_parameters','create_model','write_input_file'].includes(name)?'editing':['submit_case','sweep_parameter'].includes(name)?'running_tool':name==='digitize_density_map'?'image_tool':name==='validate_case'?'reading':name.includes('job')||name.includes('statistics')?'task_tool':'reading';return t(key);}
function updateSend(){$('send-button').disabled=!$('prompt').value.trim()||!data?.connection.ready||conversation?.request?.state==='working';$('prompt').disabled=conversation?.request?.state==='working';}
function resizePrompt(){$('prompt').style.height='auto';$('prompt').style.height=Math.min(190,Math.max(44,$('prompt').scrollHeight))+'px';updateSend();}
async function refreshBootstrap(){data=await api('/api/bootstrap?lang='+lang);translate();updateConnection();renderHistory();updateCase();renderChips();renderKnowledgeMeta();renderJobs({jobs:data.jobs});}
async function switchSession(id){storePrompt();sessionId=id;localStorage.setItem('chatgfd-session',id);conversation=await api('/api/conversation?id='+id);$('prompt').value=localStorage.getItem('aspect-prompt-'+id)||'';resizePrompt();selectedAttachments=JSON.parse(localStorage.getItem('aspect-attachments-'+id)||'[]');modelData=null;modelFilename=null;dirty=false;engine=conversation.session.engine||'aspect';$('engine-select').value=engine;renderExamples();lastMessages='';lastRequest=conversation.request?.id||'';renderHistory();updateCase();renderChips();renderConversation(true);$('sidebar-scrim').click();if(drawerMode==='model')await refreshModel();}
async function newChat(){const session=await api('/api/new',{lang,engine});data.sessions.unshift(session);await switchSession(session.id);$('prompt').focus();}
async function sendMessage(){if($('send-button').disabled)return;const prompt=$('prompt').value.trim();if(!sessionId){const files=[...selectedAttachments];await newChat();selectedAttachments=files;storeAttachments();}$('send-button').disabled=true;const result=await safe(()=>api('/api/chat',{session_id:sessionId,prompt,attachments:selectedAttachments}));if(result){selectedAttachments=[];storeAttachments();$('prompt').value='';storePrompt();resizePrompt();conversation=await api('/api/conversation?id='+sessionId);renderConversation(true);await refreshBootstrap();}else updateSend();}
function closePopovers(){$('folder-menu').classList.add('hidden');$('model-menu').classList.add('hidden');$('files-menu').classList.add('hidden');$('upload-menu').classList.add('hidden');}
function setDrawer(mode){if(drawerMode===mode)mode=null;drawerMode=mode;closePopovers();$('drawer').classList.toggle('hidden',!mode);$('app').classList.toggle('drawer-open',!!mode);$('tasks-panel').classList.toggle('hidden',mode!=='tasks');$('model-panel').classList.toggle('hidden',mode!=='model');$('drawer-title').textContent=t(mode==='tasks'?'tasks':'file_tab');if(mode==='tasks'){jobId=null;renderJobs({jobs:data.jobs});}if(mode==='model')safe(()=>refreshModel());}
function jobColor(state){return state==='succeeded'?'green':['failed','interrupted'].includes(state)?'red':['running','validating'].includes(state)?'blue':state==='queued'?'orange':'';}
function jobTime(seconds){const date=new Date(seconds*1000),pad=n=>String(n).padStart(2,'0');return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}`;}
function jobTitle(job){return job.folder||jobTime(job.created);}
function notifyJobs(jobs){const key='chatgfd-job-states-'+data.storage;let previous;try{previous=JSON.parse(localStorage.getItem(key)||'null');}catch{}if(previous){for(const j of jobs){if(previous[j.id]&&previous[j.id]!==j.state&&['succeeded','failed','interrupted','cancelled'].includes(j.state)){toast(`${jobTitle(j)} · ${t(j.state)}`,j.state!=='succeeded',12000);if(document.hidden)document.title=`${j.state==='succeeded'?'✓':'!'} ${t(j.state)} · chatGFD`;}}}localStorage.setItem(key,JSON.stringify(Object.fromEntries(jobs.map(j=>[j.id,j.state]))));}

function renderJobs(result){notifyJobs(result.jobs);if(result.online!==undefined)$('worker-state').innerHTML=`<i class="status-dot ${result.online?'green':''}"></i>${t(result.online?'worker_online':'worker_offline')}`;data.jobs=result.jobs;const active=result.jobs.filter(j=>['running','validating','queued'].includes(j.state)).length;$('task-count').textContent=active||result.jobs.length;$('tasks-label').textContent=active?t('active_runs',{count:active}):t('tasks_short');$('tasks-dot').className='status-dot '+(active?'blue':jobColor(result.jobs[0]?.state));const signature=JSON.stringify(result.jobs)+lang;if(signature!==lastJobs){lastJobs=signature;$('jobs-list').innerHTML=result.jobs.length?result.jobs.map(j=>`<div class="job-row"><div class="job-main"><div class="job-time">${jobTitle(j)}</div><div class="job-state ${j.state}"><i class="status-dot ${jobColor(j.state)}"></i>${t(j.state)}</div></div><div class="job-buttons"><button class="icon-button" data-open-job="${j.id}" title="${t('folder')}">${icon('folder')}</button><button class="icon-button" data-job="${j.id}" title="${t('job_details')}">${icon('terminal')}</button></div></div>`).join(''):`<div class="empty-state"><p>${t('no_tasks')}</p></div>`;}$('jobs-list').classList.toggle('hidden',!!jobId);$('job-detail').classList.toggle('hidden',!jobId);}
async function refreshJobDetail(){if(!jobId)return;const id=jobId,j=await api('/api/job?id='+id);if(jobId!==id)return;const html=`<button class="text-button" id="back-tasks">← ${t('back_tasks')}</button><div class="job-heading"><i class="status-dot ${jobColor(j.state)}"></i>${jobTitle(j)}</div><div class="log-toolbar"><span class="log-meta">${t(j.state)} · ${t('elapsed',{seconds:j.elapsed_seconds,cores:j.cores})}</span>${!['succeeded','failed','cancelled','interrupted'].includes(j.state)?`<button id="cancel-job" class="text-button">${t('cancel')}</button>`:''}</div>${j.note?`<div class="job-note">${esc(j.note)}</div>`:''}<pre class="log-output">${esc(j.log||j.validation_log||t('waiting_log'))}</pre><code class="path-code">${esc(j.output_directory)}</code><button class="small-primary" data-open-job="${j.id}">${t('folder')}</button>`;const scroll=$('job-detail').querySelector('.log-output')?.scrollTop||0;$('job-detail').innerHTML=html;$('job-detail').querySelector('.log-output').scrollTop=scroll;}
async function refreshModel(force=false){const id=conversation?.session.case_id;if(!id){$('model-empty').classList.remove('hidden');$('model-content').classList.add('hidden');return;}$('model-empty').classList.add('hidden');$('model-content').classList.remove('hidden');const latest=await api('/api/model?'+new URLSearchParams({id,...(modelFilename?{filename:modelFilename}:{})}));if(conversation?.session.case_id!==id)return;if(force||!modelData||modelData.case.id!==id||modelData.filename!==latest.filename){const saved=force?null:editorDrafts.get(id+':'+latest.filename);modelData=saved?{...latest,revision:saved.revision,text:saved.base}:latest;$('prm-editor').value=saved?saved.text:latest.text;dirty=!!saved;$('file-state').textContent=t(saved?(saved.revision!==latest.revision?'remote_change':'dirty'):'synced');$('file-state').classList.toggle('dirty',dirty);$('reload-model').classList.toggle('hidden',!saved||saved.revision===latest.revision);}else if(latest.revision!==modelData.revision){if(dirty){$('file-state').textContent=t('remote_change');$('reload-model').classList.remove('hidden');}else{const start=$('prm-editor').selectionStart,scroll=$('prm-editor').scrollTop;$('prm-editor').value=latest.text;$('prm-editor').selectionStart=$('prm-editor').selectionEnd=start;$('prm-editor').scrollTop=scroll;modelData=latest;}}modelData.preview=latest.preview;modelData.preview_error=latest.preview_error;$('model-path').textContent=latest.path;modelFilename=latest.filename;$('model-file-select').classList.toggle('hidden',latest.files.length<2);$('model-file-select').innerHTML=latest.files.map(f=>`<option value="${f}">${f}</option>`).join('');$('model-file-select').value=latest.filename;if(!dirty){$('file-state').textContent=t('synced');$('file-state').classList.remove('dirty');}$('save-model').disabled=!dirty;$('model-diff').classList.toggle('hidden',!conversation?.diff);if(conversation?.diff)$('model-diff').querySelector('pre').textContent=conversation.diff;}
function previewMarkup(s){const p=s.preview;let body='';if(p?.state==='succeeded'&&p.files[field]){body=`<img class="field-image" src="${p.files[field]}" alt="${t(field)}">`;}else if(p?.metadata?.field_errors?.[field]){body=`<p class="preview-wait">${esc(p.metadata.field_errors[field])}</p>`;}else if(p?.state==='failed'||s.preview_error){body=`<p class="preview-wait">${t('preview_failed')}</p><details><summary>${t('details')}</summary><pre class="job-note">${esc(p?.note||s.preview_error)}</pre></details>`;}else body=`<p class="preview-wait">${t('preview_queued')}</p>`;const notes=lang==='zh'?(p?.metadata?.notes_zh||[]):(p?.metadata?.notes||[]);return `<section class="chat-preview"><div class="preview-heading"><h3>${t('initial_fields')}</h3></div><div class="field-tabs">${['density','viscosity','temperature'].map(k=>`<button data-field="${k}" class="${field===k?'active':''}">${t(k==='viscosity'?'reference_viscosity_log':k)}</button>`).join('')}</div>${body}<details class="preview-explanation"><summary>${t('preview_note_short')}</summary><p>${t('preview_limit')}</p>${notes.map(n=>`<p>${esc(n)}</p>`).join('')}</details></section>`;}

async function saveModel(){if(!dirty)return;const result=await api('/api/save',{case_id:modelData.case.id,filename:modelData.filename,revision:modelData.revision,text:$('prm-editor').value});conversation.diff=result.diff||'';editorDrafts.delete(modelData.case.id+':'+modelData.filename);dirty=false;await refreshModel(true);toast(t('saved'));}
function openSettings(tab='connection'){closePopovers();$('settings-modal').classList.remove('hidden');selectSettings(tab);$('settings-close').focus();}
function selectSettings(tab){document.querySelectorAll('[data-settings]').forEach(b=>b.classList.toggle('active',b.dataset.settings===tab));$('connection-form').classList.toggle('hidden',tab!=='connection');$('compute-form').classList.toggle('hidden',tab!=='compute');$('knowledge-section').classList.toggle('hidden',tab!=='knowledge');if(tab==='knowledge'&&!$('kb-results').innerHTML)safe(searchKnowledge);}
function renderKnowledgeMeta(){const info=data.knowledge;const sources=data.sources.filter(s=>s.label.startsWith('paper-')||s.label.startsWith('i2vis')===(engine==='i2vis'));$('knowledge-stats').innerHTML=['documents','models','sources'].map(k=>`<div class="knowledge-stat"><strong>${Number(info[k]).toLocaleString()}</strong><span>${t('kb_'+k)}</span></div>`).join('');$('kb-source').innerHTML=`<option value="">${t('all_sources')}</option>`+sources.map(s=>`<option value="${s.label}">${t('source_'+s.label)}</option>`).join('');$('kb-kind').innerHTML=`<option value="">${t('all_kinds')}</option>`+['model','manual','benchmark','code','test','fragment'].map(k=>`<option value="${k}">${t('kind_'+k)}</option>`).join('');$('kb-sources').innerHTML=sources.map(s=>`<div class="source-entry">${esc(t('source_'+s.label))} · ${esc(s.version)}${s.role==='reference'?' · '+esc(t('reference_only')):''}<code>${esc(s.revision||s.root)}</code></div>`).join('');}
async function searchKnowledge(){const results=await api('/api/knowledge?'+new URLSearchParams({q:$('kb-search').value||t('kb_default'),source:$('kb-source').value,kind:$('kb-kind').value,engine}));$('kb-results').innerHTML=results.length?results.map(h=>`<details class="knowledge-hit"><summary>${esc(h.title||h.path)}</summary><p>${esc(t('source_'+h.source))} · ${esc(h.version)}${h.role==='reference'?' · '+esc(t('reference_only')):''}</p><pre>${esc(h.excerpt)}</pre>${h.path.endsWith('.prm')&&h.kind!=='fragment'&&h.role!=='reference'?`<button class="small-primary" data-load="${h.id}">${t('load_model')}</button>`:''}</details>`).join(''):`<p class="section-description">${t('no_matches')}</p>`;}
async function poll(){if(polling||!data)return;polling=true;try{const target=sessionId;const results=await Promise.all([target?api('/api/conversation?id='+target):Promise.resolve(null),api('/api/jobs')]);if(target===sessionId&&results[0]){const previous=conversation?.session.case_id;conversation=results[0];renderConversation();updateCase();const request=conversation.request;if(request?.state!=='working'&&request?.id!==lastRequest){lastRequest=request?.id;await refreshBootstrap();}if(previous!==conversation.session.case_id){modelData=null;modelFilename=null;dirty=false;await refreshBootstrap();if(drawerMode==='model')await refreshModel();}}renderJobs(results[1]);if(drawerMode==='tasks'&&jobId)await refreshJobDetail();if(drawerMode==='model')await refreshModel();}catch(error){if(!navigator.onLine)toast(t('connection_lost'),true);}finally{polling=false;}}
async function boot(nextLang){storePrompt();data=await api('/api/bootstrap'+(nextLang?'?lang='+nextLang:''));lang=data.lang;await api('/api/timezone',{timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'});translate();updateConnection();const cfg=data.settings;for(const [id,key] of [['task-cores','task_cores'],['total-cores','max_total_cores'],['binary','binary'],['source-root','source_root'],['mpi','mpi']])$(id).value=cfg[key];$('timeout-hours').value=cfg.timeout_seconds/3600;$('storage-path').textContent=data.storage;renderKnowledgeMeta();renderJobs({jobs:data.jobs});const remembered=localStorage.getItem('chatgfd-session')||localStorage.getItem('aspect-session-'+lang);const session=data.sessions.find(s=>s.id===remembered)||data.sessions[0];if(session)await switchSession(session.id);else{sessionId=null;conversation=null;$('prompt').value='';resizePrompt();renderHistory();renderConversation(true);updateCase();}if(drawerMode)$('drawer-title').textContent=t(drawerMode==='tasks'?'tasks':'file_tab');}

$('new-chat').onclick=()=>safe(newChat);
$('attach-button').onclick=()=>{if(!data.attachments.length){$('file-input').click();return;}const open=$('upload-menu').classList.contains('hidden');closePopovers();const box=$('attach-button').getBoundingClientRect();$('upload-menu').style.left=Math.min(box.left,window.innerWidth-220)+'px';$('upload-menu').style.top='auto';$('upload-menu').style.bottom=(window.innerHeight-box.top+8)+'px';$('upload-menu').classList.toggle('hidden',!open);};
$('upload-new').onclick=()=>{closePopovers();$('file-input').click();};
$('file-input').onchange=()=>safe(async()=>{const files=Array.from($('file-input').files);if(!files.length)return;if(!sessionId)await newChat();toast(t('uploading'));for(const file of files){if(file.size>40*1024*1024)throw Error('40 MB');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));const result=await api('/api/upload',{name:file.name,content:btoa(binary),session_id:sessionId});if(result.needs_selection)throw Error((lang==='zh'?'ZIP 中有多个参数入口，请在模型文件面板底部按路径导入：':'The ZIP has multiple PRM entries. Import a path at the bottom of the model panel:')+'\n'+result.prm_files.slice(0,8).join('\n'));if(result.id&&!selectedAttachments.includes(result.id))selectedAttachments=[...selectedAttachments,result.id].slice(0,5);}await refreshBootstrap();conversation=await api('/api/conversation?id='+sessionId);updateCase();renderConversation(true);storeAttachments();$('file-input').value='';toast(t('saved'));if(drawerMode==='model')await refreshModel(true);$('prompt').focus();});
$('history').onclick=event=>{const button=event.target.closest('[data-session]');if(button)safe(()=>switchSession(button.dataset.session));};
$('prompt').oninput=()=>{resizePrompt();storePrompt();};
$('prompt').onkeydown=event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();safe(sendMessage);}};
$('send-button').onclick=()=>safe(sendMessage);
document.querySelectorAll('[data-starter]').forEach(button=>button.onclick=()=>{$('prompt').value=starterPrompt(button.dataset.starter);resizePrompt();storePrompt();$('prompt').focus();});
$('model-picker').onclick=()=>{const open=$('model-menu').classList.contains('hidden');closePopovers();$('model-menu').classList.toggle('hidden',!open);if(open){const box=$('model-picker').getBoundingClientRect();$('model-menu').style.left=Math.max(14,Math.min(box.left,innerWidth-354))+'px';$('model-menu').style.top='auto';$('model-menu').style.bottom=(innerHeight-box.top+8)+'px';$('model-search').focus();}};
$('provider-select').onchange=()=>safe(async()=>{data.connection=await api('/api/provider',{provider:$('provider-select').value});updateConnection();});
$('model-search').oninput=renderModelOptions;
$('model-options-list').onclick=event=>{const button=event.target.closest('[data-model]');if(button){$('model-search').value=button.dataset.model;renderModelOptions();}};
$('apply-model').onclick=()=>safe(async()=>{data.connection=await api('/api/provider',{provider:$('provider-select').value,model:$('model-search').value.trim()});updateConnection();closePopovers();});
$('reuse-button').onclick=()=>safe(async()=>{if(!sessionId)await newChat();const open=$('files-menu').classList.contains('hidden');closePopovers();renderSavedFiles();$('files-menu').classList.toggle('hidden',!open);});
$('saved-files').onchange=event=>{const checkbox=event.target;if(checkbox.checked&&!selectedAttachments.includes(checkbox.value)){if(selectedAttachments.length>=5){checkbox.checked=false;toast(t('attachment_limit'),true);return;}selectedAttachments.push(checkbox.value);}else selectedAttachments=selectedAttachments.filter(id=>id!==checkbox.value);storeAttachments();};
$('attachment-chips').onclick=event=>{const button=event.target.closest('[data-remove]');if(button){selectedAttachments=selectedAttachments.filter(id=>id!==button.dataset.remove);storeAttachments();}};
$('tasks-button').onclick=()=>setDrawer('tasks');
for(const id of ['context-button'])$(id).onclick=()=>setDrawer('model');
$('drawer-close').onclick=()=>setDrawer(drawerMode);
$('tasks-panel').onclick=event=>safe(async()=>{const open=event.target.closest('[data-open-job]'),detail=event.target.closest('[data-job]');if(open)await openFolder({job_id:open.dataset.openJob});if(detail){jobId=detail.dataset.job;renderJobs({jobs:data.jobs});await refreshJobDetail();}if(event.target.closest('#back-tasks')){jobId=null;renderJobs({jobs:data.jobs});}if(event.target.closest('#cancel-job')){await api('/api/cancel',{id:jobId});await poll();}});
$('case-select').onchange=()=>safe(async()=>{if(!sessionId)await newChat();await api('/api/bind',{session_id:sessionId,case_id:$('case-select').value||null});conversation=await api('/api/conversation?id='+sessionId);dirty=false;updateCase();await refreshModel();});
$('prm-editor').oninput=()=>{dirty=$('prm-editor').value!==modelData.text;$('file-state').textContent=t(dirty?'dirty':'synced');$('file-state').classList.toggle('dirty',dirty);$('save-model').disabled=!dirty;if(dirty)editorDrafts.set(modelData.case.id+':'+modelData.filename,{text:$('prm-editor').value,base:modelData.text,revision:modelData.revision});else editorDrafts.delete(modelData.case.id+':'+modelData.filename);};
$('prm-editor').onkeydown=event=>{if(event.key==='Tab'){event.preventDefault();const input=event.target,start=input.selectionStart,end=input.selectionEnd;input.setRangeText('  ',start,end,'end');input.dispatchEvent(new Event('input'));}};
$('save-model').onclick=()=>safe(saveModel);
$('reload-model').onclick=()=>safe(async()=>{editorDrafts.delete(modelData.case.id+':'+modelData.filename);await refreshModel(true);});
$('open-model-folder').onclick=()=>safe(()=>openFolder({case_id:modelData.case.id}));
$('download-model').onclick=()=>{const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([modelData.text],{type:'text/plain'}));link.download=modelData.filename;link.click();URL.revokeObjectURL(link.href);};

$('import-local').onclick=()=>safe(async()=>{if(!sessionId)await newChat();await api('/api/import',{path:$('local-path').value,session_id:sessionId});await refreshBootstrap();conversation=await api('/api/conversation?id='+sessionId);updateCase();await refreshModel(true);});
for(const id of ['settings-nav','setup-api'])$(id).onclick=()=>openSettings();
$('settings-close').onclick=()=>{$('settings-modal').classList.add('hidden');$('api-key').value='';};
$('settings-modal').onclick=event=>{if(event.target===$('settings-modal'))$('settings-close').click();};
document.querySelectorAll('[data-settings]').forEach(button=>button.onclick=()=>selectSettings(button.dataset.settings));
$('settings-provider').onchange=()=>safe(async()=>{data.connection=await api('/api/provider',{provider:$('settings-provider').value});$('api-key').value='';updateConnection();});
$('connection-form').onsubmit=event=>{event.preventDefault();safe(async()=>{const button=event.submitter;button.disabled=true;button.textContent=t('saving');try{const result=await api('/api/connection',{provider:$('settings-provider').value,url:$('api-url').value,key:$('api-key').value});data.connection=result.connection;$('api-key').value='';updateConnection();$('connection-result').textContent=result.discovered?t('discovery_ok',{count:result.count}):t('discovery_fallback');}finally{button.disabled=false;button.textContent=t('save_connection');}});};
$('compute-form').onsubmit=event=>{event.preventDefault();safe(async()=>{await api('/api/compute',{task_cores:Number($('task-cores').value),max_total_cores:Number($('total-cores').value),hours:Number($('timeout-hours').value),binary:$('binary').value,source_root:$('source-root').value,mpi:$('mpi').value});toast(t('saved'));});};
$('kb-search-button').onclick=()=>safe(searchKnowledge);
$('kb-search').onkeydown=event=>{if(event.key==='Enter')safe(searchKnowledge);};
for(const id of ['kb-source','kb-kind'])$(id).onchange=()=>safe(searchKnowledge);
$('kb-results').onclick=event=>{const button=event.target.closest('[data-load]');if(button)safe(async()=>{if(!sessionId)await newChat();await api('/api/load',{id:Number(button.dataset.load),session_id:sessionId});await refreshBootstrap();conversation=await api('/api/conversation?id='+sessionId);updateCase();$('settings-close').click();if(drawerMode!=='model')setDrawer('model');else await refreshModel(true);});};
for(const locale of ['zh','en'])$('lang-'+locale).onclick=()=>safe(async()=>{if(lang===locale)return;await api('/api/language',{lang:locale,session_id:sessionId});await boot(locale);});
$('sidebar-open').onclick=()=>$('app').classList.add('sidebar-open');
for(const id of ['sidebar-close','sidebar-scrim'])$(id).onclick=()=>$('app').classList.remove('sidebar-open');
document.addEventListener('click',event=>{if(!event.target.closest('#model-menu,#model-picker,#files-menu,#reuse-button,#upload-menu,#attach-button'))closePopovers();});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){closePopovers();$('settings-close').click();if(drawerMode)setDrawer(drawerMode);$('app').classList.remove('sidebar-open');}});

const classic={aspect:[['classic_convection','Build a 2D thermal convection model in a 1000 × 500 km box, free-slip velocity boundaries and fixed top/bottom temperatures. Ask about missing physical values; label defaults. Generate and check the PRM without running it.','建立 1000×500 km 二维热对流模型，速度边界自由滑移，顶部与底部温度固定。先确认缺失的物理量，标明默认值，生成并检查参数文件，先不运行。'],['classic_subduction','Build a 2D visco-plastic subduction model. First align geometry, plate ages, density, flow laws and boundary velocities; explain what is assumed. Generate an editable ASPECT model.','建立二维黏塑性俯冲模型。先对齐几何、板块年龄、密度、流变律和边界速度，解释假设，再生成可编辑的 ASPECT 模型。'],['classic_tomography','Turn my uploaded tomography map into an initial model. First identify coordinates, color legend, velocity units and missing calibration. Ask me to specify or approve the velocity-to-density relation, then digitize and connect it to a compatible model.','把我上传的层析图转为初始模型。先识别坐标、色标、波速单位和缺失的标定，向我确认波速到密度的关系，然后数字化并接入兼容模型。']],i2vis:[['classic_rt','Use the bundled I2VIS rayleigh_taylor template to build my first model. Explain material density, viscosity, layer geometry and free-slip boundaries. Label teaching defaults. Generate init.t3c and mode.t3c; do not run yet.','用 I2VIS 的 rayleigh_taylor 模板建立我的第一个模型，解释材料密度、黏度、分层几何和自由滑移边界，标明教学默认值，生成 init.t3c 和 mode.t3c，先不运行。'],['classic_plume','Use the I2VIS mantle_plume template. Help me adjust the temperature anomaly, background density and viscosity, keeping the thermal expansion convention explicit. Generate and check both input files.','使用 I2VIS mantle_plume 模板，帮助我设置温度异常、背景密度和黏度，注明热膨胀约定，生成并检查两份输入文件。'],['classic_subduction','Read the I2VIS subduction template and its source-linked rheology documentation. First align plate geometry, temperature, material IDs, creep prefactors and boundary conditions with my hypothesis. Preserve units and list missing physics.','读取 I2VIS 俯冲模板及源码流变说明，先把板块几何、温度、材料编号、蠕变前因子和边界条件与假说对齐，保留单位，列出物理设定缺失项。']]};
function starterPrompt(key){if(key==='example_model')return lang==='zh'?`我想建立我的第一个 ${engine==='aspect'?'ASPECT':'I2VIS'} 动力学模型。请一步步引导我选择地质问题、几何、材料和边界条件，再生成并检查参数文件，先不要运行。`:`Help me build my first ${engine==='aspect'?'ASPECT':'I2VIS'} geodynamic model. Guide me through the geological question, geometry, materials and boundary conditions, then generate and check inputs without running.`;return t(key).replaceAll('ASPECT',engine==='aspect'?'ASPECT':'I2VIS').replaceAll('PRM',engine==='aspect'?'PRM':'init.t3c and mode.t3c');}
function renderExamples(){$('classic-example-list').innerHTML=classic[engine].map((x,i)=>`<button data-classic="${i}"><span>${t(x[0])}</span><span>↗</span></button>`).join('');$('engine-select').value=engine;renderKnowledgeMeta();}
function renderHistory(){$('history').innerHTML=data.sessions.map(s=>`<div class="history-row ${s.id===sessionId?'active':''}"><button class="history-item" data-session="${s.id}" title="${esc(s.title||t('untitled_chat'))}"><span>${esc(s.title||t('untitled_chat'))}</span></button><button class="delete-chat icon-button" data-delete="${s.id}" title="${t('delete_chat')}">${icon('close')}</button></div>`).join('')||`<p class="empty-hint">${t('no_history')}</p>`;}
function renderChatStatus(){const s=conversation?.model_status;if(!s){$('chat-status').innerHTML='';delete $('chat-status').dataset.signature;return;}const problem=s.validation?.ok===false?s.validation.summary:s.parameter_errors?.map(x=>typeof x==='string'?x:`${x.path}: ${t(x.code||'unknown_parameter')} ${x.suggestions?.join(', ')||''}`).join('\n');const p=s.physics;const missing=p?.missing?.length||0;let html=`<section class="model-card"><div class="model-card-heading"><span>${icon('file')}<strong>${esc(s.name)}</strong></span></div>${problem?`<div class="model-problem"><strong>${t('model_needs_changes')}</strong><p>${esc(problem)}</p></div>`:''}${missing?`<p class="model-problem">${t('missing_physics',{count:missing})}</p>`:''}<div class="model-card-actions"><button data-edit-current>${t('edit_parameters')}</button><button class="run-action" data-run-current>${t(s.jobs.length?'rerun_model':'run_model')}</button></div>`;
if(p?.rows?.length||missing)html+=`<details class="physics-ledger"><summary>${t('physics_alignment_title')} · ${t('alignment_'+p.state)}${missing?' · '+t('missing_count',{count:missing}):''}</summary><div class="table-scroll"><table><thead><tr>${['parameter','paper_value','page_unit','written_value','alignment_status'].map(k=>`<th>${t(k)}</th>`).join('')}</tr></thead><tbody>${p.rows.map(r=>`<tr><td>${esc(r.parameter||r.path)}</td><td>${esc(r.source_value??'—')}</td><td>${esc(r.page??'—')} · ${esc(r.source_unit||'—')}</td><td>${esc(r.actual_value??r.written_value??'—')}</td><td>${esc(t('evidence_'+r.status))}</td></tr>`).join('')}</tbody></table></div>${p.missing.map(r=>`<p>${esc(r.parameter)}: ${esc(r.reason)}</p>`).join('')}</details>`;html+='</section>';

html+=previewMarkup(s);html+=s.jobs.slice(0,5).map(j=>`<section class="inline-job"><div class="inline-job-header"><span class="job-time">${esc(jobTitle(j))}</span><span class="state-badge ${jobColor(j.state)}"><i class="status-dot ${jobColor(j.state)}"></i>${t(j.state==='validating'?'starting':j.state)}</span><button data-open-job="${j.id}" title="${t('folder')}">${icon('folder')}</button></div>${j.ended?`<p class="job-ended">${t('ended_at',{time:jobTime(j.ended)})}</p>`:''}${j.summary?`<p class="model-problem">${esc(j.summary)}</p>`:''}<details data-inline-log="${j.id}" ${openLogs.has(j.id)?'open':''}><summary>${t('job_details')}</summary><pre class="log-output" id="inline-log-${j.id}">${t('waiting_log')}</pre></details></section>`).join('');
const statusSignature=JSON.stringify([s,lang,field]);if($('chat-status').dataset.signature!==statusSignature){$('chat-status').innerHTML=html;$('chat-status').dataset.signature=statusSignature;}for(const id of openLogs)safe(async()=>{const j=await api('/api/job?id='+id);const el=$('inline-log-'+id);if(el)el.textContent=j.log||j.validation_log||j.note||t('waiting_log');});
}
async function manualRun(){if(!conversation?.session.case_id)return;const caseId=conversation.session.case_id;for(const [key,draft] of editorDrafts){if(key.startsWith(caseId+':')){const filename=key.slice(caseId.length+1);await api('/api/save',{case_id:caseId,filename,revision:draft.revision,text:draft.text});editorDrafts.delete(key);}}if(dirty){dirty=false;await refreshModel(true);}const j=await api('/api/run',{case_id:conversation.session.case_id});await poll();toast(t('run_queued'));}
$('engine-select').onchange=()=>safe(async()=>{const session=await api('/api/engine',{engine:$('engine-select').value,session_id:sessionId,lang});await refreshBootstrap();await switchSession(session.id);});
$('classic-examples').onclick=event=>{const b=event.target.closest('[data-classic]');if(b){$('prompt').value=classic[engine][Number(b.dataset.classic)][lang==='zh'?2:1];resizePrompt();storePrompt();$('prompt').focus();}};
$('history').onclick=event=>safe(async()=>{const remove=event.target.closest('[data-delete]');if(remove){await api('/api/delete-chat',{id:remove.dataset.delete});localStorage.removeItem('aspect-prompt-'+remove.dataset.delete);localStorage.removeItem('aspect-attachments-'+remove.dataset.delete);if(sessionId===remove.dataset.delete){sessionId=null;conversation=null;modelData=null;lastMessages='';}await boot(lang);return;}const b=event.target.closest('[data-session]');if(b)await switchSession(b.dataset.session);});
$('chat-status').onclick=event=>safe(async()=>{const tab=event.target.closest('[data-field]');if(tab){field=tab.dataset.field;renderChatStatus();return;}if(event.target.closest('[data-edit-current]')){if(drawerMode!=='model')setDrawer('model');await refreshModel();$('prm-editor').focus();}if(event.target.closest('[data-run-current]'))await manualRun();const folder=event.target.closest('[data-open-job]');if(folder)await openFolder({job_id:folder.dataset.openJob});});
$('chat-status').addEventListener('toggle',event=>{const el=event.target;if(el.dataset.inlineLog){if(el.open)openLogs.add(el.dataset.inlineLog);else openLogs.delete(el.dataset.inlineLog);if(el.open)safe(async()=>{const j=await api('/api/job?id='+el.dataset.inlineLog);$('inline-log-'+j.id).textContent=j.log||j.validation_log||j.note||t('waiting_log');});}},true);
$('run-model').onclick=()=>safe(manualRun);
$('model-file-select').onchange=()=>safe(async()=>{modelFilename=$('model-file-select').value;modelData=null;dirty=false;await refreshModel();});


function folderFallback(result){closePopovers();$('folder-path').textContent=result.path;$('folder-download').href=result.download_url;$('folder-menu').classList.remove('hidden');}
async function openFolder(body){const result=await api('/api/open',body);if(!result.ok){folderFallback(result);return;}if(!result.queued){toast(t('folder_opened'));return;}for(let n=0;n<14;n++){await new Promise(resolve=>setTimeout(resolve,350));const status=await api('/api/open-status?id='+result.request_id);if(status.state==='opened'){toast(t('folder_opened'));return;}if(status.state==='failed')break;}folderFallback(result);}
$('folder-close').onclick=()=>$('folder-menu').classList.add('hidden');
$('folder-copy').onclick=()=>safe(async()=>{await navigator.clipboard.writeText($('folder-path').textContent);toast(t('path_copied'));});

hydrate();safe(async()=>{await boot();renderExamples();});setInterval(poll,2000);
