'use strict';
const $=id=>document.getElementById(id);
const icons={
  aspect:'<path d="M3 19 12 4l9 15M7 13h10M5 19h14"/>',edit:'<path d="m15 4 5 5M4 20l4-1 12-12a2 2 0 0 0-4-4L4 15v5Z"/>',upload:'<path d="M12 16V3m-4 4 4-4 4 4M4 15v5h16v-5"/>',file:'<path d="M14 3H5v18h14V8l-5-5Zm0 0v5h5M8 12h8m-8 4h6"/>',settings:'<path d="m9 3-.5 3-2 1.2L4 6.5 2 10l2.5 2L4 15l2 3.5 2.5-.7 2 1.2.5 3h4l.5-3 2-1.2 2.5.7 2-3.5-2.5-2 .5-3-2-3.5-2.5.7-2-1.2-.5-3Z" transform="translate(0 -1) scale(.95)"/><circle cx="12" cy="11" r="3"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',chevron:'<path d="m7 10 5 5 5-5"/>',arrow:'<path d="M12 19V5m-6 6 6-6 6 6"/>',plus:'<path d="M12 4v16M4 12h16"/>',paperclip:'<path d="m8 13 6-6a3 3 0 0 1 4 4l-8 8a5 5 0 0 1-7-7l9-9a2 2 0 0 1 3 3l-8 8"/>',layers:'<path d="m3 8 9-5 9 5-9 5-9-5Zm0 5 9 5 9-5M3 18l9 5 9-5"/>',book:'<path d="M12 5c-3-2-6-2-10-1v15c4-1 7-1 10 1 3-2 6-2 10-1V4c-4-1-7-1-10 1Zm0 0v15"/>',sliders:'<path d="M4 7h16M4 17h16"/><circle cx="8" cy="7" r="2" fill="white"/><circle cx="16" cy="17" r="2" fill="white"/>',folder:'<path d="M3 7V4h6l3 3h9v13H3V7Z"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',terminal:'<path d="m5 6 5 6-5 6m8 0h6"/>',back:'<path d="m10 6-6 6 6 6M4 12h16"/>'
};
function icon(name){return `<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.file}</svg>`;}
function hydrate(root=document){root.querySelectorAll('[data-icon]').forEach(el=>{if(!el.querySelector('svg'))el.insertAdjacentHTML('afterbegin',icon(el.dataset.icon));});}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
let data,lang='zh',sessionId,conversation,drawerMode=null,jobId=null,modelData=null,field='density',dirty=false,polling=false,lastMessages='',lastJobs='',lastRequest='',toastTimer;
let selectedAttachments=[];
const editorDrafts=new Map();
function storePrompt(){if(sessionId)localStorage.setItem('aspect-prompt-'+sessionId,$('prompt').value);}
const token=document.querySelector('meta[name="aspect-token"]').content;
const t=(key,values={})=>{let text=data?.text[key]||key;for(const [k,v] of Object.entries(values))text=text.replaceAll(`{${k}}`,v);return text;};
async function api(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-ASPECT-Token':token},body:JSON.stringify(body)});let result=await response.json();if(!response.ok)throw Error(result.error||response.statusText);return result;}
function toast(text,error=false){$('toast').textContent=text;$('toast').classList.remove('hidden');$('toast').classList.toggle('error',error);clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),error?6500:3200);}
async function safe(fn){try{return await fn();}catch(error){toast(error.message,true);return null;}}
function translate(){$('runtime-version').textContent=data?.runtime?.version||'';document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.querySelectorAll('[data-t]').forEach(el=>el.textContent=t(el.dataset.t));document.querySelectorAll('[data-placeholder]').forEach(el=>el.placeholder=t(el.dataset.placeholder));document.querySelectorAll('[data-label]').forEach(el=>{el.title=t(el.dataset.label);el.setAttribute('aria-label',t(el.dataset.label));});$('lang-zh').classList.toggle('active',lang==='zh');$('lang-en').classList.toggle('active',lang==='en');hydrate();}
function updateConnection(){const info=data.connection;$('model-name').textContent=info.model||info.name;$('provider-select').innerHTML=data.providers.map(p=>`<option value="${p.id}">${esc(p.id==='custom'?t('custom'):p.name)}</option>`).join('');$('provider-select').value=info.id;$('settings-provider').innerHTML=$('provider-select').innerHTML;$('settings-provider').value=info.id;$('api-url').value=info.url;$('key-state').textContent=t(info.ready?'key_ready':'key_missing');$('vision-hint').textContent=t(info.vision?'vision_yes':'vision_no');$('model-search').value=info.model;$('model-options').innerHTML=info.models.map(m=>`<option value="${esc(m)}">`).join('');renderModelOptions();$('connection-hint').classList.toggle('hidden',info.ready);updateSend();}
function renderModelOptions(){const q=$('model-search').value===data.connection.model?'':$('model-search').value.toLowerCase();const list=data.connection.models.filter(m=>!q||m.toLowerCase().includes(q));$('model-options-list').innerHTML=(list.length?list:data.connection.models).map(m=>`<button class="model-option ${m===data.connection.model?'active':''}" data-model="${esc(m)}">${esc(m)}</button>`).join('');}
function renderHistory(){const items=data.sessions;$('history').innerHTML=items.length?items.map(s=>`<button class="history-item ${s.id===sessionId?'active':''}" data-session="${s.id}" title="${esc(s.title||t('untitled_chat'))}"><span>${esc(s.title||t('untitled_chat'))}</span></button>`).join(''):`<p class="empty-hint">${t('no_history')}</p>`;}
function updateCase(){const id=conversation?.session?.case_id;const name=data.cases.find(c=>c.id===id)?.name;$('context-name').textContent=name||t('model_short');$('context-button').title=name||t('model_unbound');$('case-select').innerHTML=`<option value="">${t('select_case')}</option>`+data.cases.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('case-select').value=id||'';}
function storeAttachments(){localStorage.setItem('aspect-attachments-'+sessionId,JSON.stringify(selectedAttachments));renderChips();}
function renderChips(){selectedAttachments=selectedAttachments.filter(id=>data.attachments.some(a=>a.id===id));$('attachment-chips').innerHTML=selectedAttachments.map(id=>{const a=data.attachments.find(a=>a.id===id);return `<div class="file-chip">${icon(a.kind==='pdf'?'book':'file')}<span>${esc(a.name)}</span><button data-remove="${id}" title="${t('close')}">${icon('close')}</button></div>`;}).join('');}
function renderSavedFiles(){$('saved-files').innerHTML=data.attachments.length?data.attachments.map(a=>`<label class="saved-file"><input type="checkbox" value="${a.id}" ${selectedAttachments.includes(a.id)?'checked':''}><span>${esc(a.name)}</span></label>`).join(''):`<p>${t('attachment_empty')}</p>`;}
// Escape source text first; support scientific replies without accepting raw HTML.
function inline(text){let codes=[];text=esc(text).replace(/`([^`]+)`/g,(_,c)=>`\u0000${codes.push(`<code>${c}</code>`)-1}\u0000`);text=text.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>');return text.replace(/\u0000(\d+)\u0000/g,(_,n)=>codes[n]);}
function markdown(source){const lines=source.replace(/\r/g,'').split('\n');let out='',i=0;while(i<lines.length){let line=lines[i];if(/^```/.test(line)){const code=[];i++;while(i<lines.length&&!/^```/.test(lines[i]))code.push(lines[i++]);i++;out+=`<pre><code>${esc(code.join('\n'))}</code></pre>`;continue;}if(!line.trim()){i++;continue;}if(/^#{1,6} /.test(line)){let level=Math.min(3,line.match(/^#+/)[0].length);out+=`<h${level}>${inline(line.replace(/^#+ /,''))}</h${level}>`;i++;continue;}if(line.includes('|')&&i+1<lines.length&&/^\s*\|?\s*:?-+/.test(lines[i+1])){const cells=s=>s.trim().replace(/^\||\|$/g,'').split('|').map(c=>c.trim());const heads=cells(line);i+=2;let rows='';while(i<lines.length&&lines[i].includes('|')&&lines[i].trim()){rows+='<tr>'+cells(lines[i++]).map(c=>`<td>${inline(c)}</td>`).join('')+'</tr>';}out+=`<div class="table-scroll"><table><thead><tr>${heads.map(c=>`<th>${inline(c)}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`;continue;}if(/^\s*([-*+] |\d+\. )/.test(line)){const ordered=/^\s*\d+\./.test(line);let items='';while(i<lines.length&&/^\s*([-*+] |\d+\. )/.test(lines[i]))items+=`<li>${inline(lines[i++].replace(/^\s*([-*+] |\d+\. )/,''))}</li>`;out+=`<${ordered?'ol':'ul'}>${items}</${ordered?'ol':'ul'}>`;continue;}if(/^> /.test(line)){out+=`<blockquote>${inline(line.slice(2))}</blockquote>`;i++;continue;}let para=[line];i++;while(i<lines.length&&lines[i].trim()&&!/^(#{1,6} |```|\s*[-*+] |\s*\d+\. |> )/.test(lines[i])&&!(lines[i].includes('|')&&i+1<lines.length&&/^\s*\|?\s*:?-+/.test(lines[i+1])))para.push(lines[i++]);out+=`<p>${para.map(inline).join('<br>')}</p>`;}return out;}
function renderConversation(force=false){const request=conversation?.request,working=request?.state==='working';const signature=JSON.stringify([conversation?.messages,working,request?.event,request?.error]);if(!force&&signature===lastMessages)return;lastMessages=signature;const viewport=$('chat-viewport'),nearBottom=viewport.scrollHeight-viewport.clientHeight-viewport.scrollTop<150;const empty=!conversation?.messages?.length;$('app').classList.toggle('empty',empty);$('welcome').classList.toggle('hidden',!empty);$('starters').classList.toggle('hidden',!empty);$('messages').innerHTML=(conversation?.messages||[]).map(m=>m.role==='user'?`<article class="message user"><div class="user-bubble">${esc(m.content)}</div></article>`:`<article class="message assistant"><div class="assistant-body">${markdown(m.content)}</div></article>`).join('');if(working){const name=request.event?.tool;const label=name?toolLabel(name):t('thinking');$('messages').insertAdjacentHTML('beforeend',`<div class="thinking"><i class="thinking-dot"></i><span>${esc(label)}</span></div>`);}if(request?.state==='error')$('messages').insertAdjacentHTML('beforeend',`<div class="request-error">${esc(request.error)}</div>`);updateSend();if(force||nearBottom)requestAnimationFrame(()=>{viewport.scrollTop=viewport.scrollHeight;});}
function toolLabel(name){const key=name==='search_knowledge'?'retrieving':['modify_parameters','create_model','write_input_file'].includes(name)?'editing':['submit_case','sweep_parameter'].includes(name)?'running_tool':name==='digitize_density_map'?'image_tool':name==='validate_case'?'validating_tool':name.includes('job')||name.includes('statistics')?'task_tool':'reading';return t(key);}
function updateSend(){$('send-button').disabled=!$('prompt').value.trim()||!data?.connection.ready||conversation?.request?.state==='working';$('prompt').disabled=conversation?.request?.state==='working';}
function resizePrompt(){$('prompt').style.height='auto';$('prompt').style.height=Math.min(190,Math.max(44,$('prompt').scrollHeight))+'px';updateSend();}
async function refreshBootstrap(){data=await api('/api/bootstrap?lang='+lang);translate();updateConnection();renderHistory();updateCase();renderChips();renderKnowledgeMeta();renderJobs({jobs:data.jobs});}
async function switchSession(id){storePrompt();sessionId=id;localStorage.setItem('aspect-session-'+lang,id);conversation=await api('/api/conversation?id='+id);$('prompt').value=localStorage.getItem('aspect-prompt-'+id)||'';resizePrompt();selectedAttachments=JSON.parse(localStorage.getItem('aspect-attachments-'+id)||'[]');modelData=null;dirty=false;lastMessages='';lastRequest=conversation.request?.id||'';renderHistory();updateCase();renderChips();renderConversation(true);$('sidebar-scrim').click();if(drawerMode==='model')await refreshModel();}
async function newChat(){const session=await api('/api/new',{lang});data.sessions.unshift(session);await switchSession(session.id);$('prompt').focus();}
async function sendMessage(){if($('send-button').disabled)return;const prompt=$('prompt').value.trim();if(!sessionId){const files=[...selectedAttachments];await newChat();selectedAttachments=files;storeAttachments();}$('send-button').disabled=true;const result=await safe(()=>api('/api/chat',{session_id:sessionId,prompt,attachments:selectedAttachments}));if(result){$('prompt').value='';storePrompt();resizePrompt();conversation=await api('/api/conversation?id='+sessionId);renderConversation(true);await refreshBootstrap();}else updateSend();}
function closePopovers(){$('model-menu').classList.add('hidden');$('files-menu').classList.add('hidden');}
function setDrawer(mode){if(drawerMode===mode)mode=null;drawerMode=mode;closePopovers();$('drawer').classList.toggle('hidden',!mode);$('app').classList.toggle('drawer-open',!!mode);$('tasks-panel').classList.toggle('hidden',mode!=='tasks');$('model-panel').classList.toggle('hidden',mode!=='model');$('drawer-title').textContent=t(mode==='tasks'?'tasks':'file_tab');if(mode==='tasks'){jobId=null;renderJobs({jobs:data.jobs});}if(mode==='model')safe(()=>refreshModel());}
function jobColor(state){return state==='succeeded'?'green':['failed','interrupted'].includes(state)?'red':['running','validating'].includes(state)?'blue':state==='queued'?'orange':'';}
function jobTime(seconds){const date=new Date(seconds*1000),pad=(n,w=2)=>String(n).padStart(w,'0');return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}.${pad(date.getMilliseconds(),3)}`;}
function renderJobs(result){if(result.online!==undefined)$('worker-state').innerHTML=`<i class="status-dot ${result.online?'green':''}"></i>${t(result.online?'worker_online':'worker_offline')}`;data.jobs=result.jobs;const active=result.jobs.filter(j=>['running','validating','queued'].includes(j.state)).length;$('task-count').textContent=active||result.jobs.length;$('tasks-label').textContent=active?t('active_runs',{count:active}):t('tasks_short');$('tasks-dot').className='status-dot '+(active?'blue':jobColor(result.jobs[0]?.state));const signature=JSON.stringify(result.jobs)+lang;if(signature!==lastJobs){lastJobs=signature;$('jobs-list').innerHTML=result.jobs.length?result.jobs.map(j=>`<div class="job-row"><div class="job-main"><div class="job-time">${jobTime(j.created)}</div><div class="job-state ${j.state}"><i class="status-dot ${jobColor(j.state)}"></i>${t(j.state)}</div></div><div class="job-buttons"><button class="icon-button" data-open-job="${j.id}" title="${t('folder')}">${icon('folder')}</button><button class="icon-button" data-job="${j.id}" title="${t('job_details')}">${icon('terminal')}</button></div></div>`).join(''):`<div class="empty-state"><p>${t('no_tasks')}</p></div>`;}$('jobs-list').classList.toggle('hidden',!!jobId);$('job-detail').classList.toggle('hidden',!jobId);}
async function refreshJobDetail(){if(!jobId)return;const id=jobId,j=await api('/api/job?id='+id);if(jobId!==id)return;const html=`<button class="text-button" id="back-tasks">← ${t('back_tasks')}</button><div class="job-heading"><i class="status-dot ${jobColor(j.state)}"></i>${jobTime(j.created)}</div><div class="log-toolbar"><span class="log-meta">${t(j.state)} · ${t('elapsed',{seconds:j.elapsed_seconds,cores:j.cores})}</span>${!['succeeded','failed','cancelled','interrupted'].includes(j.state)?`<button id="cancel-job" class="text-button">${t('cancel')}</button>`:''}</div>${j.note?`<div class="job-note">${esc(j.note)}</div>`:''}<pre class="log-output">${esc(j.log||j.validation_log||t('waiting_log'))}</pre><code class="path-code">${esc(j.output_directory)}</code><button class="small-primary" data-open-job="${j.id}">${t('folder')}</button>`;const scroll=$('job-detail').querySelector('.log-output')?.scrollTop||0;$('job-detail').innerHTML=html;$('job-detail').querySelector('.log-output').scrollTop=scroll;}
async function refreshModel(force=false){const id=conversation?.session.case_id;if(!id){$('model-empty').classList.remove('hidden');$('model-content').classList.add('hidden');return;}$('model-empty').classList.add('hidden');$('model-content').classList.remove('hidden');const latest=await api('/api/model?id='+id);if(conversation?.session.case_id!==id)return;if(force||!modelData||modelData.case.id!==id){const saved=force?null:editorDrafts.get(id);modelData=saved?{...latest,revision:saved.revision,text:saved.base}:latest;$('prm-editor').value=saved?saved.text:latest.text;dirty=!!saved;$('file-state').textContent=t(saved?(saved.revision!==latest.revision?'remote_change':'dirty'):'synced');$('file-state').classList.toggle('dirty',dirty);$('reload-model').classList.toggle('hidden',!saved||saved.revision===latest.revision);}else if(latest.revision!==modelData.revision){if(dirty){$('file-state').textContent=t('remote_change');$('reload-model').classList.remove('hidden');}else{const start=$('prm-editor').selectionStart,scroll=$('prm-editor').scrollTop;$('prm-editor').value=latest.text;$('prm-editor').selectionStart=$('prm-editor').selectionEnd=start;$('prm-editor').scrollTop=scroll;modelData=latest;}}modelData.preview=latest.preview;modelData.preview_error=latest.preview_error;$('model-path').textContent=latest.path;if(!dirty){$('file-state').textContent=t('synced');$('file-state').classList.remove('dirty');}$('save-model').disabled=!dirty;$('model-diff').classList.toggle('hidden',!conversation?.diff);if(conversation?.diff)$('model-diff').querySelector('pre').textContent=conversation.diff;renderPreview();}
function renderPreview(){const p=modelData?.preview;let html;if(p?.state==='succeeded'&&p.files[field]){const range=p.metadata?.ranges?.[field];html=`<img class="field-image" src="${p.files[field]}" alt="${t(field)}"><p class="field-range">${range?`${range.min.toPrecision(5)} – ${range.max.toPrecision(5)} ${field==='density'?'kg/m³':field==='viscosity'?'Pa·s':'K'}`:''}</p>`;}else if(p&&['failed','cancelled','interrupted'].includes(p.state)){html=`<div class="preview-wait">${t('preview_failed')}<pre class="job-note">${esc(p.note)}</pre></div>`;}else if(modelData?.preview_error){html=`<pre class="job-note">${esc(modelData.preview_error)}</pre>`;}else html=`<div class="preview-wait">${t('preview_queued')}</div>`;if($('preview-content').innerHTML!==html)$('preview-content').innerHTML=html;}
async function saveModel(){if(!dirty)return;const result=await api('/api/save',{case_id:modelData.case.id,revision:modelData.revision,text:$('prm-editor').value});conversation.diff=result.diff||'';editorDrafts.delete(modelData.case.id);dirty=false;await refreshModel(true);toast(t('saved'));}
function openSettings(tab='connection'){closePopovers();$('settings-modal').classList.remove('hidden');selectSettings(tab);$('settings-close').focus();}
function selectSettings(tab){document.querySelectorAll('[data-settings]').forEach(b=>b.classList.toggle('active',b.dataset.settings===tab));$('connection-form').classList.toggle('hidden',tab!=='connection');$('compute-form').classList.toggle('hidden',tab!=='compute');$('knowledge-section').classList.toggle('hidden',tab!=='knowledge');if(tab==='knowledge'&&!$('kb-results').innerHTML)safe(searchKnowledge);}
function renderKnowledgeMeta(){const info=data.knowledge;$('knowledge-stats').innerHTML=['documents','models','sources'].map(k=>`<div class="knowledge-stat"><strong>${Number(info[k]).toLocaleString()}</strong><span>${t('kb_'+k)}</span></div>`).join('');$('kb-source').innerHTML=`<option value="">${t('all_sources')}</option>`+data.sources.map(s=>`<option value="${s.label}">${t('source_'+s.label)}</option>`).join('');$('kb-kind').innerHTML=`<option value="">${t('all_kinds')}</option>`+['model','manual','benchmark','code','test','fragment'].map(k=>`<option value="${k}">${t('kind_'+k)}</option>`).join('');$('kb-sources').innerHTML=data.sources.map(s=>`<div class="source-entry">${esc(t('source_'+s.label))} · ${esc(s.version)}${s.role==='reference'?' · '+esc(t('reference_only')):''}<code>${esc(s.revision||s.root)}</code></div>`).join('');}
async function searchKnowledge(){const results=await api('/api/knowledge?'+new URLSearchParams({q:$('kb-search').value||t('kb_default'),source:$('kb-source').value,kind:$('kb-kind').value}));$('kb-results').innerHTML=results.length?results.map(h=>`<details class="knowledge-hit"><summary>${esc(h.title||h.path)}</summary><p>${esc(t('source_'+h.source))} · ${esc(h.version)}${h.role==='reference'?' · '+esc(t('reference_only')):''}</p><pre>${esc(h.excerpt)}</pre>${h.path.endsWith('.prm')&&h.kind!=='fragment'&&h.role!=='reference'?`<button class="small-primary" data-load="${h.id}">${t('load_model')}</button>`:''}</details>`).join(''):`<p class="section-description">${t('no_matches')}</p>`;}
async function poll(){if(polling||document.hidden||!data)return;polling=true;try{const target=sessionId;const results=await Promise.all([target?api('/api/conversation?id='+target):Promise.resolve(null),api('/api/jobs')]);if(target===sessionId&&results[0]){const previous=conversation?.session.case_id;conversation=results[0];renderConversation();updateCase();const request=conversation.request;if(request?.state!=='working'&&request?.id!==lastRequest){lastRequest=request?.id;await refreshBootstrap();}if(previous!==conversation.session.case_id){modelData=null;dirty=false;await refreshBootstrap();if(drawerMode==='model')await refreshModel();}}renderJobs(results[1]);if(drawerMode==='tasks'&&jobId)await refreshJobDetail();if(drawerMode==='model')await refreshModel();}catch(error){if(!navigator.onLine)toast(t('connection_lost'),true);}finally{polling=false;}}
async function boot(nextLang){storePrompt();data=await api('/api/bootstrap'+(nextLang?'?lang='+nextLang:''));lang=data.lang;translate();updateConnection();const cfg=data.settings;for(const [id,key] of [['task-cores','task_cores'],['total-cores','max_total_cores'],['binary','binary'],['source-root','source_root'],['mpi','mpi']])$(id).value=cfg[key];$('timeout-hours').value=cfg.timeout_seconds/3600;$('storage-path').textContent=data.storage;renderKnowledgeMeta();renderJobs({jobs:data.jobs});const remembered=localStorage.getItem('aspect-session-'+lang);const session=data.sessions.find(s=>s.id===remembered)||data.sessions[0];if(session)await switchSession(session.id);else{sessionId=null;conversation=null;$('prompt').value='';resizePrompt();renderHistory();renderConversation(true);updateCase();}if(drawerMode)$('drawer-title').textContent=t(drawerMode==='tasks'?'tasks':'file_tab');}

$('new-chat').onclick=()=>safe(newChat);
for(const id of ['attach-button','upload-nav'])$(id).onclick=()=>{$('file-input').click();};
$('file-input').onchange=()=>safe(async()=>{const files=Array.from($('file-input').files);if(!files.length)return;if(!sessionId)await newChat();toast(t('uploading'));for(const file of files){if(file.size>40*1024*1024)throw Error('40 MB');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));const result=await api('/api/upload',{name:file.name,content:btoa(binary),session_id:sessionId});if(result.needs_selection)throw Error((lang==='zh'?'ZIP 中有多个参数入口，请在模型文件面板底部按路径导入：':'The ZIP has multiple PRM entries. Import a path at the bottom of the model panel:')+'\n'+result.prm_files.slice(0,8).join('\n'));if(result.id&&!selectedAttachments.includes(result.id))selectedAttachments=[...selectedAttachments,result.id].slice(0,5);}await refreshBootstrap();conversation=await api('/api/conversation?id='+sessionId);updateCase();storeAttachments();$('file-input').value='';toast(t('saved'));if(drawerMode==='model')await refreshModel(true);$('prompt').focus();});
$('history').onclick=event=>{const button=event.target.closest('[data-session]');if(button)safe(()=>switchSession(button.dataset.session));};
$('prompt').oninput=()=>{resizePrompt();storePrompt();};
$('prompt').onkeydown=event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();safe(sendMessage);}};
$('send-button').onclick=()=>safe(sendMessage);
document.querySelectorAll('[data-starter]').forEach(button=>button.onclick=()=>{$('prompt').value=t(button.dataset.starter);resizePrompt();storePrompt();$('prompt').focus();});
$('model-picker').onclick=()=>{const open=$('model-menu').classList.contains('hidden');closePopovers();$('model-menu').classList.toggle('hidden',!open);if(open)$('model-search').focus();};
$('provider-select').onchange=()=>safe(async()=>{data.connection=await api('/api/provider',{provider:$('provider-select').value});updateConnection();});
$('model-search').oninput=renderModelOptions;
$('model-options-list').onclick=event=>{const button=event.target.closest('[data-model]');if(button){$('model-search').value=button.dataset.model;renderModelOptions();}};
$('apply-model').onclick=()=>safe(async()=>{data.connection=await api('/api/provider',{provider:$('provider-select').value,model:$('model-search').value.trim()});updateConnection();closePopovers();});
$('reuse-button').onclick=()=>safe(async()=>{if(!sessionId)await newChat();const open=$('files-menu').classList.contains('hidden');closePopovers();renderSavedFiles();$('files-menu').classList.toggle('hidden',!open);});
$('saved-files').onchange=event=>{const checkbox=event.target;if(checkbox.checked&&!selectedAttachments.includes(checkbox.value)){if(selectedAttachments.length>=5){checkbox.checked=false;toast(t('attachment_limit'),true);return;}selectedAttachments.push(checkbox.value);}else selectedAttachments=selectedAttachments.filter(id=>id!==checkbox.value);storeAttachments();};
$('attachment-chips').onclick=event=>{const button=event.target.closest('[data-remove]');if(button){selectedAttachments=selectedAttachments.filter(id=>id!==button.dataset.remove);storeAttachments();}};
$('tasks-button').onclick=()=>setDrawer('tasks');
for(const id of ['context-button','model-nav'])$(id).onclick=()=>setDrawer('model');
$('drawer-close').onclick=()=>setDrawer(drawerMode);
$('tasks-panel').onclick=event=>safe(async()=>{const open=event.target.closest('[data-open-job]'),detail=event.target.closest('[data-job]');if(open)await api('/api/open',{job_id:open.dataset.openJob});if(detail){jobId=detail.dataset.job;renderJobs({jobs:data.jobs});await refreshJobDetail();}if(event.target.closest('#back-tasks')){jobId=null;renderJobs({jobs:data.jobs});}if(event.target.closest('#cancel-job')){await api('/api/cancel',{id:jobId});await poll();}});
$('case-select').onchange=()=>safe(async()=>{if(!sessionId)await newChat();await api('/api/bind',{session_id:sessionId,case_id:$('case-select').value||null});conversation=await api('/api/conversation?id='+sessionId);dirty=false;updateCase();await refreshModel();});
$('prm-editor').oninput=()=>{dirty=$('prm-editor').value!==modelData.text;$('file-state').textContent=t(dirty?'dirty':'synced');$('file-state').classList.toggle('dirty',dirty);$('save-model').disabled=!dirty;if(dirty)editorDrafts.set(modelData.case.id,{text:$('prm-editor').value,base:modelData.text,revision:modelData.revision});else editorDrafts.delete(modelData.case.id);};
$('prm-editor').onkeydown=event=>{if(event.key==='Tab'){event.preventDefault();const input=event.target,start=input.selectionStart,end=input.selectionEnd;input.setRangeText('  ',start,end,'end');input.dispatchEvent(new Event('input'));}};
$('save-model').onclick=()=>safe(saveModel);
$('reload-model').onclick=()=>safe(async()=>{editorDrafts.delete(modelData.case.id);await refreshModel(true);});
$('open-model-folder').onclick=()=>safe(()=>api('/api/open',{case_id:modelData.case.id}));
$('download-model').onclick=()=>{const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([modelData.text],{type:'text/plain'}));link.download=modelData.case.name+'.prm';link.click();URL.revokeObjectURL(link.href);};
document.querySelectorAll('[data-field]').forEach(button=>button.onclick=()=>{field=button.dataset.field;document.querySelectorAll('[data-field]').forEach(b=>b.classList.toggle('active',b===button));renderPreview();});
$('import-local').onclick=()=>safe(async()=>{if(!sessionId)await newChat();await api('/api/import',{path:$('local-path').value,session_id:sessionId});await refreshBootstrap();conversation=await api('/api/conversation?id='+sessionId);updateCase();await refreshModel(true);});
for(const id of ['settings-nav','setup-api'])$(id).onclick=()=>openSettings();
$('settings-close').onclick=()=>{$('settings-modal').classList.add('hidden');$('api-key').value='';};
$('settings-modal').onclick=event=>{if(event.target===$('settings-modal'))$('settings-close').click();};
document.querySelectorAll('[data-settings]').forEach(button=>button.onclick=()=>selectSettings(button.dataset.settings));
$('settings-provider').onchange=()=>safe(async()=>{data.connection=await api('/api/provider',{provider:$('settings-provider').value});$('api-key').value='';updateConnection();});
$('connection-form').onsubmit=event=>{event.preventDefault();safe(async()=>{const button=event.submitter;button.disabled=true;button.textContent=t('saving');try{const result=await api('/api/connection',{provider:$('settings-provider').value,url:$('api-url').value,key:$('api-key').value});data.connection=result.connection;$('api-key').value='';updateConnection();$('connection-result').textContent=result.discovered?t('discovery_ok',{count:result.count}):t('discovery_fallback');}finally{button.disabled=false;button.textContent=t('save_connection');}});};
$('compute-form').onsubmit=event=>{event.preventDefault();safe(async()=>{await api('/api/compute',{task_cores:Number($('task-cores').value),max_total_cores:Number($('total-cores').value),hours:Number($('timeout-hours').value),binary:$('binary').value,source_root:$('source-root').value,mpi:$('mpi').value});toast(t('saved'));});};
$('kb-search-button').onclick=()=>safe(searchKnowledge);
$('kb-search').onkeydown=event=>{if(event.key==='Enter')safe(searchKnowledge);};
for(const id of ['kb-source','kb-kind'])$(id).onchange=()=>safe(searchKnowledge);
$('kb-results').onclick=event=>{const button=event.target.closest('[data-load]');if(button)safe(async()=>{if(!sessionId)await newChat();await api('/api/load',{id:Number(button.dataset.load),session_id:sessionId});await refreshBootstrap();conversation=await api('/api/conversation?id='+sessionId);updateCase();$('settings-close').click();if(drawerMode!=='model')setDrawer('model');else await refreshModel(true);});};
for(const locale of ['zh','en'])$('lang-'+locale).onclick=()=>safe(async()=>{if(lang===locale)return;await api('/api/language',{lang:locale});await boot(locale);});
$('sidebar-open').onclick=()=>$('app').classList.add('sidebar-open');
for(const id of ['sidebar-close','sidebar-scrim'])$(id).onclick=()=>$('app').classList.remove('sidebar-open');
document.addEventListener('click',event=>{if(!event.target.closest('#model-menu,#model-picker,#files-menu,#reuse-button'))closePopovers();});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){closePopovers();$('settings-close').click();if(drawerMode)setDrawer(drawerMode);$('app').classList.remove('sidebar-open');}});
hydrate();safe(()=>boot());setInterval(poll,2000);
